# Generated by Django 2.2.4 on 2019-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PAID', 'paid'), ('UNPAID', 'unpaid'), ('BOOKED', 'ongoing')], default='BOOKED', max_length=20),
        ),
    ]
