# Generated by Django 2.2.4 on 2019-08-21 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190820_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booked_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
