# Generated by Django 2.2.4 on 2019-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_booked_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='iga@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
