# Generated by Django 2.2.4 on 2019-08-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
