# Generated by Django 2.2.4 on 2019-08-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_email'),
        ('reservation', '0006_delete_order'),
    ]

    operations = [
    ]
