# Generated by Django 2.2.4 on 2019-08-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20190823_0920'),
        ('reservation', '0007_merge_20190823_1345'),
    ]

    operations = [
    ]
