# Generated by Django 2.2.4 on 2019-08-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='event.Event'),
        ),
    ]
