# Generated by Django 2.2.4 on 2019-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REGULAR', 'regular'), ('PREMIUM', 'premium'), ('VIP', 'VIP')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('ticket_identifier', models.CharField(max_length=10)),
            ],
        ),
    ]
