# Generated by Django 2.2.4 on 2019-08-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190821_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='seats_in_row',
            new_name='seats_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='rows',
        ),
    ]
