# Generated by Django 2.2.4 on 2019-08-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20190821_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TAKEN', 'taken'), ('FREE', 'free')], default='FREE', max_length=20),
        ),
    ]
