# Generated by Django 2.2.4 on 2019-08-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
