# Generated by Django 2.2.4 on 2019-08-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_tickets'),
        ('ticket', '0007_remove_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='seats_number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event.Event'),
        ),
    ]
